---
# tasks file for eclipse
- name: SmokeTests
  ansible.builtin.debug:
    msg:
      - "ansible_version => {{ ansible_version }}"
      - "ansible_distribution => {{ ansible_distribution }}"
      - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
      - "ansible_os_family  => {{ ansible_os_family }}"
      - "ansible_system  => {{ ansible_system }}"
